libssh: update to latest upstream git revision
OpenWrt buildbots reported this package as broken:

---snip---
[...]
Scanning dependencies of target ssh_shared
make[5]: Leaving directory `/store/buildbot/slave/mxs/build/build_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/libssh-2014-07-10'
make[5]: Entering directory `/store/buildbot/slave/mxs/build/build_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/libssh-2014-07-10'
[  2%] Building C object src/CMakeFiles/ssh_shared.dir/agent.c.o
In file included from /store/buildbot/slave/mxs/build/build_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/libssh-2014-07-10/include/libssh/agent.h:24:0,
                 from /store/buildbot/slave/mxs/build/build_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/libssh-2014-07-10/src/agent.c:52:
/store/buildbot/slave/mxs/build/build_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/libssh-2014-07-10/include/libssh/libssh.h:488:49: error: unknown type name 'mode_t'
 LIBSSH_API int ssh_mkdir (const char *pathname, mode_t mode);
[...]
---snap---

Updating to latest git revision seems to fix the build.

Signed-off-by: Michael Heimpold <mhei@heimpold.de>